export const GET_FOOD_REQUEST = "GET_FOOD_REQUEST";
export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
export const GET_FOOD_ERROR = "GET_FOOD_ERROR";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SOCIAL_REQUEST = "SOCIAL_REQUEST";
export const SOCIAL_SUCCESS = "SOCIAL_SUCCESS";
export const SOCIAL_ERROR = "SOCIAL_ERROR";

export const CART_REQUEST = "CART_REQUEST";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_ERROR = "CART_ERROR";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

export const SAVE_FOOD_PLAN_REQUEST = "SAVE_FOOD_PLAN_REQUEST";
export const SAVE_FOOD_PLAN_SUCCESS = "SAVE_FOOD_PLAN_SUCCESS";
export const SAVE_FOOD_PLAN_ERROR = "SAVE_FOOD_PLAN_ERROR";

export const SELECT_FOOD_LIST_REQUEST = "SELECT_FOOD_LIST_REQUEST";

export const SHOW_FOOD_PLAN_REQUEST = "SHOW_FOOD_PLAN_REQUEST";
export const SHOW_FOOD_PLAN_SUCCESS = "SHOW_FOOD_PLAN_SUCCESS";
export const SHOW_FOOD_PLAN_ERROR = "SHOW_FOOD_PLAN_ERROR";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";

export const PRIMARY_REQUEST = "PRIMARY_REQUEST";
export const SECONDARY_REQUEST  = "SECONDARY_REQUEST";
export const DIETARY_REQUEST = "DIETARY_REQUEST";
export const SPICY_FOOD_REQUEST = "SPICY_FOOD_REQUEST";
export const ALLERGIES_REQUEST = "ALLERGIES_REQUEST";
export const ORDER_FOR_REQUEST = "ORDER_FOR_REQUEST";
export const ORDER_TYPE_REQUEST = "ORDER_TYPE_REQUEST";
export const DELIVERY_REQUEST = "DELIVERY_REQUEST";
export const EXTRAMENTION_REQUEST = "EXTRAMENTION_REQUEST";

export const ADD_PRIMARY_REQUEST = "ADD_PRIMARY_REQUEST";
export const ADD_SECONDARY_REQUEST  = "ADD_SECONDARY_REQUEST";
export const ADD_DIETARY_REQUEST = "ADD_DIETARY_REQUEST";
export const ADD_SPICY_FOOD_REQUEST = "ADD_SPICY_FOOD_REQUEST";
export const ADD_ALLERGIES_REQUEST = "ADD_ALLERGIES_REQUEST";
export const ADD_ORDER_FOR_REQUEST = "ADD_ORDER_FOR_REQUEST";
export const ADD_ORDER_TYPE_REQUEST = "ADD_ORDER_TYPE_REQUEST";
export const ADD_DELIVERY_REQUEST = "ADD_DELIVERY_REQUEST";
export const ADD_EXTRAMENTION_REQUEST = "ADD_EXTRAMENTION_REQUEST";
export const ADD_BREAKFAST_TIME_INTERVAL_REQUEST = "ADD_BREAKFAST_TIME_INTERVAL_REQUEST";
export const ADD_DINNER_TIME_INTERVAL_REQUEST = "ADD_DINNER_TIME_INTERVAL_REQUEST";
export const ADD_LUNCH_TIME_INTERVAL_REQUEST = "ADD_LUNCH_TIME_INTERVAL_REQUEST";


export const UPDATE_PRIMARY_REQUEST = "UPDATE_PRIMARY_REQUEST";
export const UPDATE_SECONDARY_REQUEST  = "UPDATE_SECONDARY_REQUEST";
export const UPDATE_DIETARY_REQUEST = "UPDATE_DIETARY_REQUEST";
export const UPDATE_SPICY_FOOD_REQUEST = "UPDATE_SPICY_FOOD_REQUEST";
export const UPDATE_ALLERGIES_REQUEST = "UPDATE_ALLERGIES_REQUEST";
export const UPDATE_ORDER_FOR_REQUEST = "UPDATE_ORDER_FOR_REQUEST";
export const UPDATE_ORDER_TYPE_REQUEST = "UPDATE_ORDER_TYPE_REQUEST";
export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_EXTRAMENTION_REQUEST = "UPDATE_EXTRAMENTION_REQUEST";

export const UPDATE_QUESTIONNAIRE_DATA = "UPDATE_QUESTIONNAIRE_DATA";

export const ALLERGIESLIST_REQUEST = "ALLERGIESLIST_REQUEST";
export const ALLERGIESLIST_SUCCESS = "ALLERGIESLIST_SUCCESS";
export const ALLERGIESLIST_ERROR = "ALLERGIESLIST_ERROR";
